# Generated by Django 3.0.2 on 2020-01-31 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('post_intro', models.TextField(blank=True)),
                ('post_body', models.TextField(blank=True)),
                ('post_summary', models.TextField(blank=True)),
                ('image', models.ImageField(default='default_for_articles.jpg', upload_to='article_pictures')),
                ('creation_date', models.TimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='Food.Products')),
            ],
        ),
    ]
