# Generated by Django 3.0.2 on 2020-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet_prod',
            field=models.ManyToManyField(related_name='diet_set', to='User.UserProd'),
        ),
    ]
