# Generated by Django 3.0.2 on 2020-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20200202_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='slug',
            field=models.CharField(blank=True, max_length=55, unique=True),
        ),
    ]
