# Generated by Django 3.0.2 on 2020-02-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_meals_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='ingredients_weights',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='meals',
            name='slug',
            field=models.CharField(blank=True, max_length=81, unique=True),
        ),
    ]
