# Generated by Django 3.0.2 on 2020-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_auto_20200203_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='ingredient',
            field=models.ManyToManyField(related_name='products', to='Food.Products'),
        ),
    ]
